### ISSUE TITLE
postFollow not working with Location header present

### ISSUE THREAD

**Issue by johnnypea** [badgateway/ketting#264]
I can't make `postFollow()` even when my API returns correct headers.
`Error: Could not follow after a 201 request, because the server did not reply with a Location header`

Response Headers
```
access-control-allow-origin: http://localhost:3000
access-control-expose-headers: link
cache-control: max-age=0, must-revalidate, private
content-length: 129
content-location: /api/cars/128
content-type: application/json; charset=utf-8
date: Mon, 05 Oct 2020 15:02:44 GMT
expires: Mon, 05 Oct 2020 15:02:44 GMT
link: <https://localhost:8000/api/docs.jsonld>; rel="http://www.w3.org/ns/hydra/core#apiDocumentation"
location: /api/cars/128
set-cookie: sf_redirect=%7B%22token%22%3A%22130830%22%2C%22route%22%3A%22api_cars_post_collection%22%2C%22method%22%3A%22POST%22%2C%22controller%22%3A%22api_platform.action.post_collection%22%2C%22status_code%22%3A201%2C%22status_text%22%3A%22Created%22%7D; path=/; secure; httponly; samesite=lax
status: 201
vary: Accept
x-content-type-options: nosniff
x-debug-token: 130830
x-debug-token-link: https://localhost:8000/_profiler/130830
x-frame-options: deny
x-powered-by: PHP/7.4.11
x-robots-tag: noindex
```

I did brief debugging and it looks like `response.headers` are always empty 😕. Data are posted and saved in the database as expected.

Thanks.

**Comment by johnnypea** [comment]
Sorry, my bad. The wrong configuration in my Symfony API Platform app, was missing `expose_headers: ['Link', 'Location']` (https://github.com/nelmio/NelmioCorsBundle).

This is my config as now, maybe somebody will find it usefull:
```
nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: []
        allow_headers: []
        allow_methods: []
        expose_headers: []
        max_age: 0
        hosts: []
        origin_regex: false
        forced_allow_origin_value: ~
    paths:
        '^/api/':
            origin_regex: true
            allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
            allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
            allow_headers: ['Content-Type', 'Authorization', 'Accept', 'User-Agent']
            expose_headers: ['Link', 'Location']
            max_age: 3600
        '^/': null
```
